puts "The students of the Academy of Evil"
puts "--------------------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Micheal Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Kruger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
